name: findyourdresse_app
description: findyourdresse
publish_to: none
version: 1.0.5+8
environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=2.5.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  geoflutterfire: ^3.0.3
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  shared_preferences: ^2.0.20
  cloud_firestore: ^3.3.0
  cloud_functions: ^3.3.2
  firebase_storage: ^10.3.2
  firebase_messaging: ^12.0.0
  firebase_core_platform_interface: 4.5.1
  dartdoc: null
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  auto_route: ^4.2.1
  url_strategy: ^0.2.0
  hooks_riverpod: ^1.0.3
  get_it: ^7.2.0
  get: ^4.6.5
  dartz: ^0.10.1
  responsive_framework: ^0.2.0
  flutter_screenutil: ^5.5.3+2
  easy_localization: ^3.0.1
  fluttertoast: 8.1.2
  path: 1.8.2
  mime_type: ^1.0.0
  expandable_page_view: ^1.0.17
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.1
  flutter_local_notifications: ^9.7.0
  connectivity_plus: ^3.0.2
  uuid: ^3.0.6
  flutter_svg: ^1.1.1+1
  flutter_native_splash: ^2.2.18
  sliding_up_panel: ^2.0.0+1
  toggle_switch: ^2.0.1
  flutter_typeahead: 4.1.1
  google_maps_flutter: ^2.2.0
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  reorderables: ^0.5.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^2.0.0
  app_settings: ^4.1.8
  share_plus: 4.5.3
  algolia: ^1.1.1
  video_thumbnail: ^0.5.3
  datetime_picker_formfield_new: ^2.0.0
  video_player: ^2.5.1
  chewie: ^1.4.0
  core_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  geolocator: ^9.0.2
  form_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  skeleton_kosmos:
    git:
      url: YOUR_URL
      ref: main
  package_signalement:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  timeago: ^3.3.0
  timeago_flutter: ^1.2.0
  notification_kosmos:
    git:
      url: YOUR_URL
      ref: main
  firebase_in_app_messaging: ^0.6.0+27
  firebase_app_installations: ^0.1.1+10
  purchases_flutter: 4.8.0
  iconsax: ^0.0.8
  permission_handler: ^10.2.0
  readmore: ^2.2.0
  multiselect: ^0.1.0
  flutter_pdfview: ^1.3.0
  flutter_widget_from_html: null
  csslib: 0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.3
  auto_route_generator: ^4.2.0
  json_serializable: ^6.2.0
  carousel_slider: ^4.1.1
flutter_native_splash:
  background_image: assets/images/native_splash.png
  ios: false
  android_12:
    color: '#FFFFFF'
flutter:
  uses-material-design: true
  fonts:
  - family: PlayfairDisplay
    fonts:
    - asset: assets/fonts/PlayfairDisplay-Regular.ttf
      weight: 400
    - asset: assets/fonts/PlayfairDisplay-Medium.ttf
      weight: 500
    - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/PlayfairDisplay-Bold.ttf
      weight: 700
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Light.ttf
      weight: 300
    - asset: assets/fonts/Poppins-Regular.ttf
      weight: 400
    - asset: assets/fonts/Poppins-Medium.ttf
      weight: 500
    - asset: assets/fonts/Poppins-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Poppins-Bold.ttf
      weight: 700
  assets:
  - assets/svg/
  - assets/images/
  - assets/translations/
  - assets/legalDoc/
